## my global config
#global:
#  scrape_interval:     120s # By default, scrape targets every 15 seconds.
#  evaluation_interval: 120s # By default, scrape targets every 15 seconds.
#
## A scrape configuration containing exactly one endpoint to scrape:
## Here it's Prometheus itself.
#scrape_configs:
#  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'prometheus'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    # metrics_path defaults to '/metrics'
#    # scheme defaults to 'http'.
#    static_configs:
#      - targets: ['localhost:9090','core:8080','localhost:9100', 'localhost:9113']
#
#  - job_name: 'Spring Boot Application input'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 2s
#    static_configs:
#      - targets: ['core:8080']
#        labels:
#          application: "My Spring Boot Application"
---
global:
  scrape_interval: 120s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['myapp-service-9090.default.svc.cluster.local:9090', 'myapp-service-8080.default.svc.cluster.local:8080']  # Адреса внутри Kubernetes кластера

  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['myapp-service-8080.default.svc.cluster.local:8080']  # Адрес вашего Spring Boot приложения внутри кластера
        labels:
          application: "My Spring Boot Application"
