version: '3'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    domainname: core
    container_name: core
    ports:
      - "8080:8080"
    restart: always
    networks:
      - some-net
  prometheus:
    build:
      context: ./prom
      dockerfile: Dockerfile
    domainname: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - some-net
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    domainname: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - some-net
networks:
  some-net: